# Generated by Django 3.2.19 on 2023-06-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlikes',
            name='likes',
            field=models.IntegerField(choices=[(1, 'like'), (-1, 'dislike')], default=0),
        ),
    ]
