# Generated by Django 3.2.19 on 2023-06-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview', '0002_alter_reviewlikes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_likes',
        ),
    ]
